// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Smoking.DAL.Data;

#nullable disable

namespace Smoking.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611060848_InitialPostgresCreate")]
    partial class InitialPostgresCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Smoking.DAL.Entities.Achievement", b =>
                {
                    b.Property<int>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AchievementID"));

                    b.Property<string>("AchievementName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BadgeImage")
                        .HasColumnType("text");

                    b.Property<int?>("CheckinDaysRequired")
                        .HasColumnType("integer");

                    b.Property<int?>("CigarettesDroppedRequired")
                        .HasColumnType("integer");

                    b.Property<string>("Criteria")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("MoneySavedRequired")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PackageType")
                        .HasColumnType("text");

                    b.Property<int?>("SmokeFreeDaysRequired")
                        .HasColumnType("integer");

                    b.HasKey("AchievementID");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.AnswerOption", b =>
                {
                    b.Property<int>("AnswerOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerOptionID"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionID")
                        .HasColumnType("integer");

                    b.HasKey("AnswerOptionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlogId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("BlogType")
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dislikes")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlogId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.BlogReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsLike")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("BlogReaction");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.ConsultationBooking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CoachID")
                        .HasColumnType("integer");

                    b.Property<string>("CoachNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("BookingID");

                    b.HasIndex("CoachID");

                    b.HasIndex("UserID");

                    b.ToTable("ConsultationBooking");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("FeedbackContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackID");

                    b.HasIndex("UserID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.MembershipPackage", b =>
                {
                    b.Property<int>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PackageID");

                    b.ToTable("MembershipPackage");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Milestone", b =>
                {
                    b.Property<int>("MilestoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MilestoneID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MilestoneGroupID")
                        .HasColumnType("integer");

                    b.Property<int>("MilestoneTime")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Percent")
                        .HasColumnType("integer");

                    b.Property<string>("TimeUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MilestoneID");

                    b.HasIndex("MilestoneGroupID");

                    b.ToTable("Milestone");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.MilestoneGroup", b =>
                {
                    b.Property<int>("MilestoneGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MilestoneGroupID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MilestoneGroupID");

                    b.ToTable("MilestoneGroup");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotificationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.PackageMilestone", b =>
                {
                    b.Property<int>("PackageMilestoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageMilestoneID"));

                    b.Property<string>("DetailDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MilestoneID")
                        .HasColumnType("integer");

                    b.Property<int>("PackageID")
                        .HasColumnType("integer");

                    b.HasKey("PackageMilestoneID");

                    b.HasIndex("MilestoneID");

                    b.HasIndex("PackageID");

                    b.ToTable("PackageMilestone");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PackageID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UserMembershipID")
                        .HasColumnType("integer");

                    b.HasKey("PaymentID");

                    b.HasIndex("PackageID");

                    b.HasIndex("UserID");

                    b.HasIndex("UserMembershipID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitChallengeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("NotesSuggestion")
                        .HasColumnType("text");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("StageTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuitChallengeTemplate");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitPlan", b =>
                {
                    b.Property<int>("QuitPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuitPlanID"));

                    b.Property<int>("CigarettesPerDayAtStart")
                        .HasColumnType("integer");

                    b.Property<int>("CigarettesPerPack")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerPackAtStart")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("QuitPlanID");

                    b.HasIndex("UserID");

                    b.ToTable("QuitPlan");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitPlanSelectedAnswers", b =>
                {
                    b.Property<int>("SelectedAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SelectedAnswerID"));

                    b.Property<int>("AnswerOptionID")
                        .HasColumnType("integer");

                    b.Property<string>("CustomAnswerText")
                        .HasColumnType("text");

                    b.Property<int>("QuitPlanID")
                        .HasColumnType("integer");

                    b.HasKey("SelectedAnswerID");

                    b.HasIndex("AnswerOptionID");

                    b.HasIndex("QuitPlanID");

                    b.ToTable("QuitPlanSelectedAnswers");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitProgress", b =>
                {
                    b.Property<int>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgressID"));

                    b.Property<int?>("CigarettesDropped")
                        .HasColumnType("integer");

                    b.Property<int>("CigarettesPerDayBaseline")
                        .HasColumnType("integer");

                    b.Property<int?>("CigarettesSmokedToday")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSmokeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MoneySaved")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProgressDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuitPlanID")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalCigarettesDropped")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalMoneySaved")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ProgressID");

                    b.HasIndex("QuitPlanID");

                    b.ToTable("QuitProgress");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.SmokingStatus", b =>
                {
                    b.Property<int>("SmokingStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SmokingStatusID"));

                    b.Property<int>("CigarettesPerDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerPack")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("SmokingStatusID");

                    b.HasIndex("UserID");

                    b.ToTable("SmokingStatuses");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("CoachChangeReason")
                        .HasColumnType("text");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("PendingCoachId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserID");

                    b.HasIndex("CoachId");

                    b.HasIndex("PendingCoachId");

                    b.HasIndex("RoleID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Smoking.DAL.Entities.UserMembership", b =>
                {
                    b.Property<int>("UserMembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserMembershipID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PackageID")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("UserMembershipID");

                    b.HasIndex("PackageID");

                    b.HasIndex("UserID");

                    b.ToTable("UserMembership");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.UserMilestoneProgress", b =>
                {
                    b.Property<int>("UserMilestoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserMilestoneID"));

                    b.Property<DateTime?>("AchievedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MilestoneID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("UserMilestoneID");

                    b.HasIndex("MilestoneID");

                    b.HasIndex("UserID");

                    b.ToTable("UserMilestoneProgress");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.UserQuitChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChallengeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("QuitPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuitPlanId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuitChallenge");
                });

            modelBuilder.Entity("UserAchievement", b =>
                {
                    b.Property<int>("UserAchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserAchievementID"));

                    b.Property<int>("AchievementID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AwardedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("UserAchievementID");

                    b.HasIndex("AchievementID");

                    b.HasIndex("UserID");

                    b.ToTable("UserAchievement");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.AnswerOption", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Blog", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.BlogReaction", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.Blog", "Blog")
                        .WithMany("BlogReactions")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("BlogReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.ConsultationBooking", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.User", "Coach")
                        .WithMany("ConsultationBookingsAsCoach")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("ConsultationBookingsAsUser")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Feedback", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Milestone", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.MilestoneGroup", "MilestoneGroup")
                        .WithMany("Milestones")
                        .HasForeignKey("MilestoneGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MilestoneGroup");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Notification", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.PackageMilestone", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.Milestone", "Milestone")
                        .WithMany("PackageMilestones")
                        .HasForeignKey("MilestoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.MembershipPackage", "Package")
                        .WithMany("PackageMilestones")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Payment", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.MembershipPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.UserMembership", "UserMembership")
                        .WithMany("Payments")
                        .HasForeignKey("UserMembershipID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Package");

                    b.Navigation("User");

                    b.Navigation("UserMembership");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitPlan", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("QuitPlans")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitPlanSelectedAnswers", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.AnswerOption", "AnswerOption")
                        .WithMany()
                        .HasForeignKey("AnswerOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.QuitPlan", "QuitPlan")
                        .WithMany()
                        .HasForeignKey("QuitPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("QuitPlan");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitProgress", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.QuitPlan", "QuitPlan")
                        .WithMany("QuitProgresses")
                        .HasForeignKey("QuitPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuitPlan");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.SmokingStatus", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("SmokingStatuses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.User", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.User", "Coach")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Smoking.DAL.Entities.User", "PendingCoach")
                        .WithMany()
                        .HasForeignKey("PendingCoachId");

                    b.HasOne("Smoking.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");

                    b.Navigation("PendingCoach");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.UserMembership", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.MembershipPackage", "Package")
                        .WithMany("UserMemberships")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("UserMemberships")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.UserMilestoneProgress", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.Milestone", "Milestone")
                        .WithMany("UserMilestoneProgresses")
                        .HasForeignKey("MilestoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("UserMilestoneProgresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.UserQuitChallenge", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.QuitPlan", "QuitPlan")
                        .WithMany()
                        .HasForeignKey("QuitPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.QuitChallengeTemplate", "Template")
                        .WithMany("UserChallenges")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuitPlan");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserAchievement", b =>
                {
                    b.HasOne("Smoking.DAL.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smoking.DAL.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Blog", b =>
                {
                    b.Navigation("BlogReactions");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.MembershipPackage", b =>
                {
                    b.Navigation("PackageMilestones");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Milestone", b =>
                {
                    b.Navigation("PackageMilestones");

                    b.Navigation("UserMilestoneProgresses");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.MilestoneGroup", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitChallengeTemplate", b =>
                {
                    b.Navigation("UserChallenges");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.QuitPlan", b =>
                {
                    b.Navigation("QuitProgresses");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.User", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("BlogReactions");

                    b.Navigation("Blogs");

                    b.Navigation("ConsultationBookingsAsCoach");

                    b.Navigation("ConsultationBookingsAsUser");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");

                    b.Navigation("QuitPlans");

                    b.Navigation("SmokingStatuses");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserMemberships");

                    b.Navigation("UserMilestoneProgresses");
                });

            modelBuilder.Entity("Smoking.DAL.Entities.UserMembership", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
